version: 0.2

phases:
  install:
    commands:
      # install terraform binary
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  pre_build:
    commands:
      - pip install --target ./package requests
    finally:
      - echo This always runs even if the login command fails
  build:
    commands:
      - cd package
      - zip -r ../${ENV_PREFIX}-lambda-package.zip .
      - cd ..
      - zip -g ${ENV_PREFIX}-lambda-package.zip ./*.py
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      # insert the terraform secret
      - sed -i 's/[$]{TOKEN}/'${tf_token}'/' creds.tf
      - mv creds.tf ~/.terraformrc

      # insert the environment ENV_PREFIX
      - sed -i 's/[$]{PREFIX}/'${ENV_PREFIX}'/g' LambdaDeploy.tf

      # insert the package file
      - sed -i 's/[$]{PACKAGE}/'${ENV_PREFIX}'-lambda-package.zip/g' LambdaDeploy.tf

      # Run the terraform
      - terraform init
      - terraform plan
